services:
  - type: web
    name: Youth Management System
    env: static
    buildCommand: npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_ENV
        value: production